paths:
  data:
    TRAIN_IMAGE_FOLDER: ./data/train
    TRAIN_METADATA: ./data/train.csv
    PREPROCESSED_CACHE: ./data/preprocessed/X_y.npz
  model:
    MODEL_FOLDER: ./data/models

RANDOM_STATE_N: 19

tensorboard:
  SERVER_PORT: 6006
  LOG_DIR: logs