paths:
  data:
    TRAIN_IMAGE_FOLDER: ./data/input/train
    TRAIN_METADATA: ./data/input/train.csv
    PREPROCESSED_CACHE: ./data/working/preprocessed/X_and_y.pkl
    TEST_IMAGE_FOLDER: ./data/input/test
  model:
    MODEL_FOLDER: ./data/working/models

RANDOM_STATE_N: 19

tensorboard:
  SERVER_PORT: 6006
  LOG_DIR: logs
